
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icinga
  namespace: {{ monitoring_ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icinga
  template:
    metadata:
      labels:
        app: icinga
    spec:
      containers:
        - name: icinga
          image: jordan/icinga2:latest
          ports:
            - containerPort: 80
          env:
            - name: ICINGA_ADMIN_USER
              value: "icingaadmin"
            - name: ICINGA_ADMIN_PASS
              value: "icinga123"
---
apiVersion: v1
kind: Service
metadata:
  name: icinga
  namespace: {{ monitoring_ns }}
spec:
  selector:
    app: icinga
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
